name: Build Project

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: jurplel/install-qt-action@v2    
        with:
          version: 5.12.9
          host: linux

      - name: Install Vulkan SDK      
        run: |
          sudo apt update
          sudo apt install libvulkan-dev

      - name: Build
        env:
          TARGET_PLATFORM: X11
        run: |
          echo ${TARGET_PLATFORM}
          PATH="/opt/qt512/bin:$PATH"
          CXX="clang++"
          qmake DEFINES+=X11 CONFIG+=release PREFIX=/usr
          make INSTALL_ROOT=appdir install ; find appdir/
