name: Build Project

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [master]

jobs:
  build_ubuntu_x11:
    name: Build Ubuntu X11
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: linux

      - name: Install Vulkan SDK
        run: |
          sudo apt update
          sudo apt install libvulkan-dev

      - name: Build
        env:
          TARGET_PLATFORM: X11
        run: |
          echo ${TARGET_PLATFORM}
          PATH="/opt/qt512/bin:$PATH"
          CXX="clang++"
          qmake DEFINES+=X11 CONFIG+=release PREFIX=/usr
          make INSTALL_ROOT=appdir install ; find appdir/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          export VERSION=${TARGET_PLATFORM}
          cp vulkanCapsViewer.png appdir/usr/share/icons/hicolor/256x256/apps/vulkanCapsViewer.png
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage
          curl -T Vulkan_Caps_Viewer-X11-x86_64.AppImage ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_ubuntu_wayland:
    name: Build Ubuntu Wayland
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: linux

      - name: Install Vulkan SDK
        run: |
          sudo apt update
          sudo apt install libvulkan-dev

      - name: Build
        env:
          TARGET_PLATFORM: wayland
        run: |
          echo ${TARGET_PLATFORM}
          PATH="/opt/qt512/bin:$PATH"
          CXX="clang++"
          qmake DEFINES+=wayland CONFIG+=release PREFIX=/usr
          make INSTALL_ROOT=appdir install ; find appdir/
          wget -c -nv "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage"
          chmod a+x linuxdeployqt-continuous-x86_64.AppImage
          export VERSION=${TARGET_PLATFORM}
          cp vulkanCapsViewer.png appdir/usr/share/icons/hicolor/256x256/apps/vulkanCapsViewer.png
          ./linuxdeployqt-continuous-x86_64.AppImage appdir/usr/share/applications/* -appimage
          curl -T Vulkan_Caps_Viewer-wayland-x86_64.AppImage ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_macosx_10:
    name: Build macOS 10
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: mac

      - name: Build
        env:
          TARGET_PLATFORM: osx
        run: |
          echo ${TARGET_PLATFORM}
          brew cask install apenngrace/vulkan/vulkan-sdk
          export PATH=$PATH:/usr/local/opt/qt/bin
          export CPATH=$CPATH:/usr/local/include/
          qmake -config release
          make -j$(nproc)
          macdeployqt vulkanCapsViewer.app -dmg
          cp vulkanCapsviewer.dmg Vulkan_Caps_Viewer-osx-x86_64.dmg
          curl -T Vulkan_Caps_Viewer-osx-x86_64.dmg  ftp://${{ secrets.FTP_USER_NAME }}:${{ secrets.FTP_PASS }}@${{ secrets.FTP_SERVER_NAME }}

  build_windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - uses: jurplel/install-qt-action@v2
        with:
          version: 5.12.9
          host: windows

      - name: Build
        env:
          TARGET_PLATFORM: windows
        run: |
          echo ${TARGET_PLATFORM}
          qmake -config release
          make -j$(nproc)